services:
  database:
    container_name: mongo_db
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_DATABASE=product_order
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - database-data:/data/db

volumes:
  database-data:

networks:
  mongo-network:
    driver: bridge